version: '3.9'
services:
  app:
    build: .
    ports:
      - "57802:57802"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      # Path to SQLite database inside the container
      DB_PATH: /app/data/app.db
